# -*- coding: utf-8 -*-
"""Brincando.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1N2QMSuUlSw7THDJaBYKPO4OjrCyK3bkU
"""

# aula python

pessoa = 'verusca silva'
print(pessoa)

pessoa ='verusca'
idade =34 
altura = 1.56
print('ola',pessoa,'voce tem',idade,'anos',altura,"de altura")

numero = 12
numero2 = 34
soma= numero + numero2
soma

decimal =15/4
print(decimal)

variavel = 0
variavel2 = 99
print(variavel +variavel2)

nome = 'ana'
sobrenome = 'silva'
print(nome,sobrenome)

valor = 100
valor2= 0.3
div = valor/valor2
print (div)

x= 5
y= 7
z= 0
media=(x+y+z)/3
print(media)



x= 5
y= 7
z= 12
media=(x+y+z)/3
print(media)